# -*- coding: utf-8 -*-
"""covid 19.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2aJjXSXI6ZHVh_wEp7-3DG6lc9XtY6A
"""

!pip install pandas numpy matplotlib seaborn plotly

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

sns.set()

url = "https://raw.githubusercontent.com/datasets/covid-19/main/data/countries-aggregated.csv"

df = pd.read_csv(url)
df.head()

df.columns = ['Date', 'Country', 'Confirmed', 'Recovered', 'Deaths']


df['Date'] = pd.to_datetime(df['Date'])


df['Active'] = df['Confirmed'] - df['Recovered'] - df['Deaths']

df.head()

print("Total Confirmed:", df['Confirmed'].sum())
print("Total Deaths:", df['Deaths'].sum())
print("Total Recovered:", df['Recovered'].sum())

df.describe()

trend = df.groupby('Date')[['Confirmed', 'Deaths', 'Recovered']].sum().reset_index()

plt.figure()
plt.plot(trend['Date'], trend['Confirmed'])
plt.title("Confirmed Cases Over Time")
plt.xlabel("Date")
plt.ylabel("Cases")
plt.xticks(rotation=45)
plt.show()

top_countries = df.groupby('Country')[['Confirmed']].max().sort_values(by='Confirmed', ascending=False).head(10)

top_countries.plot(kind='bar')
plt.title("Top 10 Affected Countries")
plt.show()

latest = df.groupby('Country').max().sort_values(by='Confirmed', ascending=False).head(5)

plt.figure()
plt.pie(latest['Confirmed'], labels=latest.index, autopct='%1.1f%%')
plt.title("Top 5 Countries")
plt.show()

plt.figure()
plt.scatter(df['Confirmed'], df['Deaths'])
plt.xlabel("Confirmed")
plt.ylabel("Deaths")
plt.title("Confirmed vs Deaths")
plt.show()

corr = df[['Confirmed', 'Deaths', 'Recovered', 'Active']].corr()

sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()